[우현제]백준 10951(A+B), 9093(문장 단어 뒤집기)
wooritech/wooricamp-whj pull request #27
Opened 2024-10-30 04:59 UTC by Hjname

# 10951번 문제

boj2.spec.js 파일의 testCases1 변수 데이터를 사용하여 실행합니다.

```
const testCases1 = [
    [1, 1],
    [2, 3],
    [3, 4],
    [9, 8],
    [5, 2],
    [9, 9], // 조건 내 최대값
    [-1, -5], // 음수
    [100, 999], // 조건 초과
    [1.11, 3.2] // 소수점
];
```
실행 결과
```
2
5
7
17
7
18
-6
1099
4.3100000000000005
```
소수점을 사용한 테스트에서 예상 외의 결과가 출력되었습니다.

# 9093번 문제

boj2.spec.js 파일의 testCases2 변수 데이터를 사용하여 실행합니다.

```
const testCases2 = [
    '8',
    'I am happy today',
    'We want to win the first prize',
    'Nursery rhyme and Mother Goose', // 대문자 혼용하기
    'What are little boys made of?', // 특수 기호 사용하기
    'Frogs and snails',
    'And puppys tails',
    'That is what little boys are made of',
    'qwertyuiopasdfghjklzxcvbnm', // 단어 길이 제한 초과
];
```
실행결과
```
I ma yppah yadot
eW tnaw ot niw eht tsrif ezirp
yresruN emyhr dna rehtoM esooG
tahW era elttil syob edam ?fo
sgorF dna slians
dnA syppup sliat
tahT si tahw elttil syob era edam fo
mnbvcxzlkjhgfdsapoiuytrewq
```
문제없이 뒤집혀 나오는 것을 확인 할 수 있습니다.

# 코딩컨벤션 설정

## .prettierrc 파일 설정

들여쓰기 간격을 4로 설정합니다.
`"tabWidth": 4` 
문자열을 싱글 퀘테이션으로 감쌉니다.
`"singleQuote": true`

Format Document를 실행한 결과 적용 되는것을 확인하였습니다.

## eslint 파일 설정

변수 미할당시 에러를 발생시킵니다.
"no-unused-vars": "error"
재할당 되지 않는 변수를 let으로 선언할 경우 에러를 발생시킵니다.
"prefer-const": "error"

boj2.js 파일에서 적용 여부를 확인했을때  둘다 적용되었습니다.

<img width="651" alt="스크린샷 2024-10-30 오후 1 34 04" src="https://github.com/user-attachments/assets/55fef4ca-b106-4db4-9c94-28d9356ca065">

# 어려웠던 부분

코딩컨벤션의 eslint 설정시 처음 작성했던 설정이 적용이 안되서 결국 재설치 과정을 밟으면서 작성했다.

2024-11-01 06:53 UTC, WooriPbg requested changes
jest를 사용해 테스트 코드를 작성한 게 안 보이네요 추가해 주세요

2024-11-01 06:53 UTC, WooriPbg commented on .gitignore
> +package.json
package.json 파일을 왜 gitignore에 추가 했나요?

2024-11-01 06:53 UTC, WooriPbg commented on back_joon/boj2/boj2.js
> +}
sum 함수를 만들 거면 testCase를 인자로 받는 게 좋지 않을까요?
sum이라는 뜻은 더하다는 뜻인데 console에 출력만 하고 끝나는 게 sum 함수 같지 않습니다.
더한 값을 return 해주고 밖에서 console에 출력해 주는 게 더 좋을 거 같습니다.

2024-11-01 06:53 UTC, WooriPbg commented on back_joon/boj2/boj2.js
> +}
sum 함수와 마찬가지로 인자로 값을 받은 다음 뒤집은 결과를 리턴해주는 게 더 적절해 보입니다.

2024-11-04 02:34 UTC, Hjname commented on .gitignore
> +package.json
문제 풀이에 관한 내용만 올리기 위해 gitignore에 추가하였습니다.

2024-11-06 01:29 UTC, closed without merging